# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore
  categories:
    - title: 🎉 New Features
      labels:
        - 🍍 algorithms
        - 🚂 operators
    - title: 📝 Documentation updates
      labels:
        - documentation

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
