# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore
      - 💩 wontfix
  categories:
    - title: 🎉 Algorithms and Operators
      labels:
        - 🍍 algorithms
        - 🚂 operators
        - ⚖️ load-balancing
        - 🐲 enhancement
    - title: 🐛 Bug Fixes
      labels:
        - 🐛 bug
    - title: 🏡 API Changes/Improvements
      labels:
        - 🏡 api
        - 🏭 build
    - title: 📝 Documentation Updates
      labels:
        - 📋 documentation
    - title: 🧪 Testing
      labels:
        - 🧪 testing
        - 🔬 experiment
        - 📼 i/o

autolabeler:
  - label: '📋 documentation'
    files:
      - '*.md'
